from xmldiff import main
## Both PS_Module_v2p1.xml and ModuleTest_settings_test.xml are downloaded and generated by "python3 makeXml.py" 
xml1 = "PS_Module_v2p1.xml"
xml2 = "ModuleTest_settings_test.xml" ## generated from makeXml.py with PS_Module_settings_test.py 
xml2 = "ModuleTest_settings.xml" ## generated from moduleTest.py

diff = main.diff_files(xml1, xml2)
print(f"    Comparing {xml1} with {xml2}")
for a in diff:
   if not "comment()" in a.node: ##ignore changes in comments
       print(a)
