config = {'Nevents': 1000,
 'boards': {0: {'ip': 'fc7ot3:50001',
                'opticalGroups': {0: {'hybrids': {0: {'pixels': [8,
                                                                 9,
                                                                 10,
                                                                 11,
                                                                 12,
                                                                 13,
                                                                 14,
                                                                 15],
                                                      'strips': [0,
                                                                 1,
                                                                 2,
                                                                 3,
                                                                 4,
                                                                 5,
                                                                 6,
                                                                 7]},
                                                  1: {'pixels': [8,
                                                                 9,
                                                                 10,
                                                                 11,
                                                                 12,
                                                                 13,
                                                                 14,
                                                                 15],
                                                      'strips': [0,
                                                                 1,
                                                                 2,
                                                                 3,
                                                                 4,
                                                                 5,
                                                                 6,
                                                                 7]}},
                                      'lpGBT': 'lpGBT_v1_PS.txt'}}}}}